import {StyleSheet} from 'react-native';
import AppColor from '../../Constant/AppColor';
import sizeHelper from '../../Helpers/sizeHelper';

export const styles = StyleSheet.create({
  mainContainer: {
    // flex:1,
    width: '100%',
    height: '100%',
    backgroundColor: AppColor.white1,
  },
  CardContainer: {
    alignSelf: 'center',
    width: '92%',
    height: 'auto',
    backgroundColor: AppColor.white,
    borderRadius: sizeHelper.calHp(20),
    padding: sizeHelper.calHp(15),
    marginVertical: sizeHelper.calHp(20),
    borderLeftWidth: sizeHelper.calHp(10),
    borderColor: AppColor.blue,
  },
  topView: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: sizeHelper.calHp(10),
  },
  leaveType: {
    fontSize: sizeHelper.calHp(24),
    color: AppColor.black2,
    fontFamily: 'InterMedium',
    textTransform: 'capitalize',
  },
  Status: {
    fontSize: sizeHelper.calHp(20),
    textTransform: 'capitalize',
    color: AppColor.white,
    fontFamily: 'InterMedium',
    paddingVertical: sizeHelper.calHp(10),
    paddingHorizontal: sizeHelper.calHp(15),
    borderRadius: sizeHelper.calHp(50),
  },
  bottomView: {
    // width:'90%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: sizeHelper.calHp(15),
    overflow: 'hidden',
    borderTopWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: AppColor.gray4,
    width: '100%',
  },
  date: {
    fontSize: sizeHelper.calHp(20),
    color: AppColor.gray5,
    fontFamily: 'InterMedium',
    textTransform: 'capitalize',
  },
  aproval: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '55%',
    borderLeftWidth: 1.5,
    height: sizeHelper.calHp(70),
    borderStyle: 'dashed',
    borderColor: AppColor.gray4,
    justifyContent: 'flex-end',
  },
  aprovalBy: {
    textTransform: 'capitalize',
    fontSize: sizeHelper.calHp(24),
    color: AppColor.gray5,
    fontFamily: 'InterMedium',
    paddingHorizontal: sizeHelper.calHp(10),
  },
  dashLine: {
    height: '120%',
    width: 1,
    borderLeftWidth: 2,
    borderStyle: 'dashed',
    borderColor: AppColor.gray4,
    position: 'absolute',
    alignSelf: 'center',
  },
  Description: {
    fontSize: sizeHelper.calHp(22),
    color: AppColor.black1,
    fontFamily: 'InterRegular',
    lineHeight: sizeHelper.calHp(25),
  },
  NotFoundContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  notfoundImg: {
    width: sizeHelper.calHp(250),
    height: sizeHelper.calHp(250),
    resizeMode: 'contain',
  },
  hiddenItemContainer: {
    flex: 1,
    height: sizeHelper.calHp(300),
    flexDirection: 'row',
    justifyContent: 'flex-end',
    borderRadius: sizeHelper.calHp(15),
    overflow: 'hidden',
    marginVertical: sizeHelper.calHp(20),
    backgroundColor: AppColor.red,
    width: '90%',
    height: 'auto',
    borderRadius: sizeHelper.calHp(20),
    left: sizeHelper.calWp(30)
  },
  deleteButton: {
    backgroundColor: AppColor.red,
    justifyContent: 'center',
    alignItems: 'center',
    width: sizeHelper.calWp(100),
    borderRadius: sizeHelper.calHp(15),
  },
});
